# Site settings
title: Reed`s Blog
SEOTitle: Reed`s Blog
header-img: images/background.jpg
email: admin@mrwang.pw
description: "But things evolve ,they change , people change."
keyword: "Spring, Java, Linux, Canvas, Reading, Spring cloud, Spring boot, Blog, Life,
 Ruby, Windows, Network, Unarchived, Algorithm"
url: "https://yonghaowang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/YonghaoWang/YonghaoWang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Thinking is hard but relinquishing is easy"
sidebar-avatar: /images/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    YonghaoWang
#facebook_username:  baiying.qiu.7
jianshu_username:   de7f25ee2679
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: bb75adacf35e5b2aad77                            #生成的clientID
  clientSecret: 736bf5ada3b55ad12fcc021e74bdc86e02fe64b9    #生成的clientSecret
  repo: YonghaoWang.github.io    #仓库名称
  owner: YonghaoWang    #github用户名
  admin: YonghaoWang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 访客
leancloud:
  enable: true
  app_id: uRWCOWGDoz7BXy74wjhrOLNp-gzGzoHsz
  app_key: TFw8qQPQPB7c6g15Wnz4oRWB

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 83b30a47d8ee39fdb8f02263d0663d60

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 3              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    #     title: "WY",
    #     href: "http://zhengwuyang.com"
    # },{
    #     title: "简书·BY",
    #     href: "http://www.jianshu.com/u/e71990ada2fd"
    # },{
    #     title: "Apple",
    #     href: "https://apple.com"
    # },{
    #     title: "Apple Developer",
    #     href: "https://developer.apple.com/"
    # }
]
